config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"), #home page urls
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"), #about page urls
    path("support/", TemplateView.as_view(template_name="pages/support.html"), name="support"), #support page urls

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # User management
    path("users/", include("simspro.users.urls", namespace="users")), #users urls
    path("accounts/", include("allauth.urls")), #urls for authentication purposes
    # Your stuff: custom urls includes go here
    path("main/", include("simspro.main.urls", namespace="main")), #main app urls
    path("setup/", include("simspro.setup.urls", namespace="setup")), #setup app urls
    path("employee/", include("simspro.employee.urls", namespace="employee")), #employee urls
    path("parents/", include("simspro.parents.urls", namespace="parents")), #parents urls
    path("students/", include("simspro.students.urls", namespace="students")), #students urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

simspro/main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = "main"
urlpatterns = [
    path('dashboard', views.user_dashboard, name='user_dashboard'),
    path('reports', views.reports, name='reports'),
]

simspro/parents/urls.py
from django.contrib.auth import views as auth_views
from simspro.parents import views
from django.urls import include, path

app_name = "parents"

urlpatterns = [
    path('parents/', views.AddParentView.as_view(), name='add_parent'),
     path('parent/update/', views.ParentUpdateView.as_view(), name='parent_update'),
]

simspro/setup/urls.py
from django.contrib.auth import views as auth_views
from simspro.setup import views
from django.urls import include, path

app_name = "setup"

urlpatterns = [
    path('setup/', views.AddFeesView.as_view(), name='add_fees'),
]

simspro/users/urls.py
from django.contrib.auth import views as auth_views
from simspro.users import views
from django.urls import include, path

app_name = "users"
urlpatterns = [
    path('user/update/', views.UserUpdateView.as_view(), name='user_update'),
]

simspro/main/models.py
from django.db import models

# Create your models here.

simspro/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

class User(AbstractUser):
    is_admin = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_secretary = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_student = models.BooleanField(default=False)
    is_parent = models.BooleanField(default=False)
    middle_name = models.CharField(max_length=1000, blank=True, null=True, verbose_name='Middle Name')

    def get_absolute_url(self):
        return reverse("users:user_update", kwargs={"username": self.username})

simspro/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth import forms as frms
User = get_user_model()
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm #We import the ModelForm class, which will do all the heavy lifting for us.
from allauth.account.forms import SignupForm

class UserChangeForm(frms.UserChangeForm):
    class Meta(frms.UserChangeForm.Meta):
        model = User

class UserCreationForm(frms.UserCreationForm):

    error_message = frms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(frms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

class UserUpdateForm(ModelForm): #UserUpdateForm class inherits from ModelForm.
        username = forms.CharField(required=False, disabled=True)
        email = forms.EmailField(required=False, disabled=True)
        first_name = forms.CharField(required=False, disabled=True)
        middle_name = forms.CharField(required=False, disabled=True)
        last_name = forms.CharField(required=False, disabled=True)
        is_superuser = forms.BooleanField(required=False, disabled=True)
        is_staff = forms.BooleanField(required=False, disabled=True)
        is_active = forms.BooleanField(required=False, disabled=True)
        is_parent = forms.BooleanField(required=False, disabled=True)
        is_admin = forms.BooleanField(required=False, disabled=True)
        is_teacher = forms.BooleanField(required=False, disabled=True)
        is_secretary = forms.BooleanField(required=False, disabled=True)
        is_student = forms.BooleanField(required=False, disabled=True)
        date_joined = forms.CharField(required=False, disabled=True)

        class Meta: #The ModelForm class has an internal Meta class which we use to pass in the metadata options the ModelForm class needs to render our form:
            model = User
            fields = ['username', 'email', 'first_name', 'middle_name', 'last_name', 'is_superuser', 'is_staff', 'is_active', 'is_parent',
            'is_admin', 'is_teacher', 'is_secretary', 'is_student', 'date_joined']

            help_texts = {
            'username': None,
            'is_superuser': None,
             }

simspro/employee/views.py
from django.contrib import messages
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from simspro.employee.forms import AddEmployeeForm, EmployeeUpdateForm
from django.contrib.auth import get_user_model
User = get_user_model()
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from .models import Employees

# Create your views here.

class AddEmployeeView(LoginRequiredMixin, CreateView):
    model = User
    form_class = AddEmployeeForm
    template_name = 'employee/add_employee.html'
    success_url = reverse_lazy('add_employee')

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'employee'
        return super().get_context_data(**kwargs)
    
    def get_success_url(self):
        return reverse("employee:add_employee")

    def form_valid(self, form):
        #form.instance.created_by.set([self.request.user])
        messages.add_message(self.request, messages.SUCCESS, ("New employee details have been successfully added!"))
        return super().form_valid(form)

class EmployeeUpdateView(LoginRequiredMixin, UpdateView):
    model = Employees
    form_class = EmployeeUpdateForm
    template_name = 'employee/employee_update_form.html'
    success_url = reverse_lazy('employee_update')

    def get_success_url(self):
        return reverse("employee:employee_update")#, kwargs={"username": self.request.user.username})

    def get_object(self):
        return Employees.objects.get(user=self.request.user)
       
    def form_valid(self, form):
        #form.instance.modified_by.set([self.request.user])
        messages.add_message(
            self.request, messages.INFO, _("The employee information have been successfully updated")
        )
        return super().form_valid(form)

simspro/main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

#We are going to create a new view to display a template when a user logs in.
@login_required
def user_dashboard(request):
    return render(request, 'main/dashboard.html')

#We are going to create a new view to display a template for reports.
@login_required
def reports(request):
    return render(request, 'main/reports.html')

simspro/parents/views.py
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView
from simspro.parents.forms import AddParentForm, ParentUpdateForm
from django.contrib.auth import get_user_model
User = get_user_model()
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Parents

# Create your views here.

class AddParentView(CreateView, LoginRequiredMixin):
    model = User
    form_class = AddParentForm
    template_name = 'parents/add_parent.html'
    #success_url = reverse_lazy('account_login')

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'parent'
        return super().get_context_data(**kwargs)
    
    #def get_success_url(self):
        #return reverse("users:account_login")

    def form_valid(self, form):
        user = form.save(form)
        #form.instance.created_by.set([self.request.user]) 
        login(self.request, user)#Redirect to login after the form is successfully submitted!
        messages.add_message(self.request, messages.SUCCESS, ("Your New Account Has Been Successfully Created. You Can Now login."))
        return super().form_valid(form)

class ParentUpdateView(LoginRequiredMixin, UpdateView):
    model = Parents
    form_class = ParentUpdateForm
    template_name = 'parents/parent_update_form.html'
    success_url = reverse_lazy('parent_update')

    def get_success_url(self):
        return reverse("parent:parent_update")#, kwargs={"username": self.request.user.username})

    def get_object(self):
        return Parents.objects.get(user=self.request.user)
       
    def form_valid(self, form):
        #form.instance.modified_by.set([self.request.user])
        messages.add_message(self.request, messages.INFO, ("The parent information have been successfully updated"))
        return super().form_valid(form)
        

simspro/setup/views.py
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import Fees
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django import forms

class AddFeesView(LoginRequiredMixin, CreateView):
    model = Fees
    template_name = 'setup/add_fees.html'
    fields = ('fee_code', 'fee_description', 'fee_amount', 'academic_year', 'term', 'grade_level')
    success_url = reverse_lazy('add_fees')

    def get_success_url(self):
        return reverse("setup:add_fees")
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        messages.add_message(self.request, messages.SUCCESS, ("The Fee Instance Has Been Successfully Created."))
        return super().form_valid(form)

simspro/students/views.py
from django.contrib import messages
#from django.shortcuts import render
#from django.contrib.auth import login
#from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView
from simspro.students.forms import AddStudentForm, StudentUpdateForm
from django.contrib.auth import get_user_model
User = get_user_model()
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.urls import reverse_lazy
from simspro.students.models import Students

# Create your views here.

class AddStudentView(LoginRequiredMixin, CreateView):
    model = User
    form_class = AddStudentForm
    template_name = 'students/add_student.html'
    success_url = reverse_lazy('add_student')

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)
    
    def get_success_url(self):
        return reverse("students:add_student")

    def form_valid(self, form):
        #form.instance.created_by.set([self.request.user]) 
        messages.add_message(self.request, messages.SUCCESS, ("The Student Details Have Been Successfully Added."))
        return super().form_valid(form)

class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Students
    form_class = StudentUpdateForm
    template_name = 'students/student_update_form.html'
    success_url = reverse_lazy('student_update')

    def get_success_url(self):
        return reverse("students:student_update")#, kwargs={"username": self.request.user.username})

    def get_object(self):
        return Students.objects.get(user=self.request.user)
       
    def form_valid(self, form):
        #form.instance.modified_by.set([self.request.user])
        messages.add_message(
            self.request, messages.INFO, _("The student information have been successfully updated")
        )
        return super().form_valid(form)
        

simspro/templates/employee/views.py
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import CreateView
from simspro.employee.forms import AddEmployeeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
User = get_user_model()
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from .models import Employees

# Create your views here.

class AddEmployeeView(LoginRequiredMixin, CreateView):
    model = User
    form_class = AddEmployeeForm
    template_name = 'employee/add_employee.html'
    success_url = reverse_lazy('add_employee')

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'employee'
        return super().get_context_data(**kwargs)
    
    def get_success_url(self):
        return reverse("employee:add_employee")

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, ("New employee details have been successfully added!"))
        return super().form_valid(form)

class EmployeeDetailView(LoginRequiredMixin, DetailView):
    model = Employees
    slug_field = "username"
    slug_url_kwarg = "username"
employee_detail_view = EmployeeDetailView.as_view()

class EmployeeUpdateView(LoginRequiredMixin, UpdateView):
    model = Employees
    fields = ['title', 'employee_number', 'employee_phone', 'designation', 'gender', 'date_of_birth', 'religion', 'language', 'nationality',
    'qualification', 'address', 'teacher_profile_summary', 'marital_status', 'spouse_name', 'spouse_email', 'spouse_phone']

    def get_success_url(self):
        return reverse("employee:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return Employees.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("The employee information have been successfully updated")
        )
        return super().form_valid(form)

employee_update_view = EmployeeUpdateView.as_view()

class EmployeeRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("employee:detail", kwargs={"username": self.request.user.username})

employee_redirect_view = EmployeeRedirectView.as_view()

simspro/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import UpdateView
User = get_user_model()
from django.urls import reverse
from django.urls import reverse_lazy
from simspro.users.forms import UserUpdateForm

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/user_update_form.html'
    success_url = reverse_lazy('user_update')

    def get_success_url(self):
        return reverse("users:user_update") #kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        #form.instance.modified_by.set([self.request.user])
        messages.add_message(
            self.request, messages.INFO, _("The personal information have NOT been updated.  To update your personal details, please contact your administrator.")
        )
        return super().form_valid(form)

simspro/templates/parents/add_parent.html
{% extends "master_layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
Parent | Sign Up
{% endblock title %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h3 class="card-title"><i class="fas fa-user-plus"></i>  Create Account</h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
        <i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
        <i class="fas fa-times"></i></button>
    </div>
  </div>
  <div class="card-body">
    <form class="signup" id="signup_form" method="post" action="{% url 'parents:add_parent' %}" novalidate>
      {% csrf_token %}
    
      <div class="form-row">
        <div class="form-group col-md-6 mb-0">
          {{ form.username|as_crispy_field }}
        </div>
    
        <div class="form-group col-md-6 mb-0">
            {{ form.email|as_crispy_field }}
          </div>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-6 mb-0">
            {{ form.first_name|as_crispy_field }}
        </div>
    
        <div class="form-group col-md-6 mb-0">
            {{ form.last_name|as_crispy_field }}   
        </div>
      </div>
    
    
      <div class="form-row">
        <div class="form-group col-md-6 mb-0">
          {{ form.parent_phone|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
          {{ form.gender|as_crispy_field }}
        </div>
    
      </div>
    
      <div class="form-row">
        <div class="form-group col-md-6 mb-0">
          {{ form.password1|as_crispy_field }}
        </div>
    
        <div class="form-group col-md-6 mb-0">
          {{ form.password2|as_crispy_field }}
        </div>
      </div>
      <button class="btn btn-primary" type="submit">{% trans "Create New Account" %} &raquo;</button>
    </form>
  
  </div>
  <!-- /.card-body -->
  
  <!-- /.card-footer-->
</div>
<!-- /.card -->
{% endblock %}

simspro/templates/parents/parent_update_form.html
{% extends "master_layout.html" %}
{% load crispy_forms_tags %}

{% block title %}simspro.net | {{ user.username }}{% endblock %}

{% block content %}

<div class="card">
  <div class="card-header">
    <h3 class="card-title"><i class="fas fa-users"></i> Update employee details </h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
        <i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
        <i class="fas fa-times"></i></button>
    </div>
  </div>
  <div class="card-body">

  <form class="form-horizontal" method="post" action="{% url 'parents:parent_update' %}">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.title|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.designation|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.gender|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.religion|as_crispy_field }}
      </div>
    </div>
    
    <div class="form-row">
      <div class="form-group col-md-4 mb-0">
        {{ form.parent_number|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.date_of_birth|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.language|as_crispy_field }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.nationality|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.qualification|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.marital_status|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.parent_phone|as_crispy_field }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.address|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.parent_profile_summary|as_crispy_field }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-4 mb-0">
        {{ form.spouse_name|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.spouse_email|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.spouse_phone|as_crispy_field }}
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update Parent Information</button>
      </div>
    </div>
  </form>
</div>
<!-- /.card-body -->
<div class="card-footer">
  <p class="text-danger">NB: Disabled (greyed out) fields can only be updated by contacting the School administrator.</p>
</div>
<!-- /.card-footer-->
</div>
<!-- /.card -->
{% endblock %}